/** Static technical data sheets for each Ecuadorian export product. */

export interface FichaTecnica {
  nombreCientifico?: string;
  familia?: string;
  hsCode: string;
  origen: string;
  regionProduccion: string;
  puertoExportacion: string;
  temporadaDisponible: string;
  certificaciones: string[];
  especificaciones: Record<string, string>;
  empaque: Record<string, string>;
  almacenamiento: Record<string, string>;
  infoNutricional?: Record<string, string>;
  observaciones?: string;
}

const FICHAS: Record<string, FichaTecnica> = {
  /* ─────────────────── AGRÍCOLAS ─────────────────── */

  'banano-cavendish-premium': {
    nombreCientifico: 'Musa acuminata (Cavendish)',
    familia: 'Musaceae',
    hsCode: '0803.90.10',
    origen: 'Ecuador',
    regionProduccion: 'Los Ríos, Guayas, El Oro, Esmeraldas',
    puertoExportacion: 'Puerto de Guayaquil',
    temporadaDisponible: 'Todo el año',
    certificaciones: ['GlobalGAP', 'Rainforest Alliance', 'Orgánico', 'Comercio Justo', 'HACCP'],
    especificaciones: {
      'Calibre (mm)': '36 – 46 mm de diámetro',
      Longitud: '18 – 22 cm mínimo',
      'Color de exportación': 'Verde PANTONE 357/359 (Etapa 1)',
      'Grados Brix (madurez)': '20 – 22 °Brix',
      Firmeza: 'Grado 1 – 2 (escala USDA)',
      'Defectos máximos': '≤ 2% de pulpa afectada',
      'Humedad relativa': '85 – 90 %',
      Variedad: 'Cavendish Williams / Gran Naine',
    },
    empaque: {
      'Caja estándar': 'Cartón corrugado de doble pared',
      'Peso neto por caja': '18.14 kg',
      Configuración: '4 manos / racimos por caja',
      'Bolsa interior': 'Polietileno perforado',
      'Presentaciones especiales': '13.5 kg, 18.14 kg, 20 kg',
      Etiquetado: 'PLU sticker + código de país de origen',
      Pallet: '1,000 kg / pallet estándar EUR 1.2×0.8 m',
    },
    almacenamiento: {
      'Temperatura de transporte': '13 – 14 °C',
      'Temperatura de maduración': '15 – 18 °C',
      'Humedad relativa': '85 – 90 %',
      'Vida útil (exportación)': '21 – 28 días desde cosecha',
      'Atmósfera controlada': 'CO₂ 2 – 5 %, O₂ 2 – 5 %',
      Etileno: 'Sensible – evitar exposición',
    },
    infoNutricional: {
      Energía: '89 kcal / 100 g',
      Proteína: '1.1 g',
      'Grasa total': '0.3 g',
      Carbohidratos: '22.8 g',
      'Fibra dietética': '2.6 g',
      Azúcares: '12.2 g',
      Potasio: '358 mg',
      'Vitamina C': '8.7 mg',
      'Vitamina B6': '0.4 mg',
    },
    observaciones:
      'Ecuador es el mayor exportador mundial de banano. La zona de producción cumple con protocolo SESA para exportación a UE, EE.UU. y Asia.',
  },

  'platano-verde': {
    nombreCientifico: 'Musa paradisiaca',
    familia: 'Musaceae',
    hsCode: '0803.10.00',
    origen: 'Ecuador',
    regionProduccion: 'Los Ríos, Esmeraldas, Manabí, Guayas',
    puertoExportacion: 'Puerto de Guayaquil',
    temporadaDisponible: 'Todo el año',
    certificaciones: ['GlobalGAP', 'Comercio Justo', 'HACCP'],
    especificaciones: {
      Calibre: '35 – 55 mm de diámetro',
      Longitud: '20 – 35 cm',
      Grado: 'A / Extra',
      Color: 'Verde uniforme, sin manchas',
      Madurez: 'Grado 1 – 2 (sin maduración)',
      'Grados Brix': '< 3 °Brix (verde)',
      Defectos: '≤ 3 % superficie afectada',
    },
    empaque: {
      'Peso neto por caja': '20 – 22 kg',
      'Tipo de caja': 'Cartón corrugado',
      'Bolsa interior': 'Polietileno',
      'Presentación alternativa': 'A granel en pallets con malla',
      Pallet: '1,100 kg / pallet',
    },
    almacenamiento: {
      Temperatura: '12 – 14 °C',
      'Humedad relativa': '88 – 92 %',
      'Vida útil': '14 – 21 días desde cosecha',
      Etileno: 'Sensible – evitar mezcla con frutas maduras',
    },
    infoNutricional: {
      Energía: '122 kcal / 100 g',
      Proteína: '1.3 g',
      'Grasa total': '0.4 g',
      Carbohidratos: '31.9 g',
      'Fibra dietética': '2.3 g',
      Potasio: '499 mg',
      'Vitamina C': '18.4 mg',
    },
  },

  'aguacate-hass-premium': {
    nombreCientifico: 'Persea americana Mill. cv. Hass',
    familia: 'Lauraceae',
    hsCode: '0804.40.00',
    origen: 'Ecuador',
    regionProduccion: 'Imbabura, Pichincha, Loja, Carchi',
    puertoExportacion: 'Puerto de Guayaquil / Aeropuerto Quito (aéreo)',
    temporadaDisponible: 'Mayo – Diciembre (pico: Julio – Octubre)',
    certificaciones: ['GlobalGAP', 'HACCP', 'Orgánico', 'Rainforest Alliance'],
    especificaciones: {
      'Peso por fruta': '150 – 350 g (calibres 12 – 20)',
      'Materia seca': '≥ 21 %',
      'Contenido de grasa': '18 – 22 %',
      'Color exterior': 'Verde oscuro a negro en madurez',
      'Firmeza de exportación': 'Grado 1 (firmeza 4 – 6 kg/cm²)',
      'Tolerancia de defectos': '≤ 2 % de la superficie',
      Variedad: 'Hass (clon premium injertado)',
    },
    empaque: {
      'Caja estándar': '4 kg y 10 kg cartón corrugado',
      Alternativa: '23 kg caja telescópica',
      Distribución: '4 / 5 / 6 / 7 / 8 / 10 frutos por caja',
      'Bolsa interior': 'Polipropileno microperforado',
      Etiquetado: 'PLU + código de barras + origen',
      Pallet: 'EUR 1.2 × 0.8 m, 80 – 100 cajas',
    },
    almacenamiento: {
      Temperatura: '4 – 7 °C',
      'Humedad relativa': '85 – 90 %',
      'Vida útil': '28 – 35 días post cosecha',
      'Atmósfera controlada': 'CO₂ 3 – 10 %, O₂ 2 – 5 %',
      Precaución: 'Sensible a daño por frío < 4 °C',
    },
    infoNutricional: {
      Energía: '160 kcal / 100 g',
      Proteína: '2.0 g',
      'Grasa total': '14.7 g',
      'Ácidos grasos monoinsaturados': '9.8 g',
      Carbohidratos: '8.5 g',
      'Fibra dietética': '6.7 g',
      Potasio: '485 mg',
      'Vitamina K': '21 µg',
      Folato: '81 µg',
    },
  },

  'mango-tommy-atkins': {
    nombreCientifico: 'Mangifera indica L. cv. Tommy Atkins',
    familia: 'Anacardiaceae',
    hsCode: '0804.50.20',
    origen: 'Ecuador',
    regionProduccion: 'Guayas, Manabí, El Oro, Los Ríos',
    puertoExportacion: 'Puerto de Guayaquil',
    temporadaDisponible: 'Noviembre – Febrero (principal); Mayo – Julio (segunda)',
    certificaciones: ['GlobalGAP', 'HACCP', 'Orgánico'],
    especificaciones: {
      'Peso por fruto': '300 – 600 g',
      'Grados Brix': '14 – 18 °Brix',
      'Color exterior': 'Rojo-verde con amarillo en madurez',
      Firmeza: 'Grado A (resistente al transporte)',
      'Madurez de cosecha': '80 – 90 % fisiológico',
      'Defectos máximos': '≤ 2 %',
      Tolerancia: 'Calibre 8 – 16 frutos / caja 4 kg',
    },
    empaque: {
      'Caja 4 kg': '8 – 16 frutos según calibre',
      'Caja 10 kg': '18 – 30 frutos',
      Tipo: 'Cartón corrugado doble pared',
      Bandeja: 'Termoformada individual por fruta',
      Pallet: '80 cajas / pallet EUR',
    },
    almacenamiento: {
      Temperatura: '8 – 10 °C (verde-pintón)',
      'Temperatura maduración': '15 – 18 °C',
      'Humedad relativa': '85 – 90 %',
      'Vida útil': '21 – 28 días post cosecha',
      Sensibilidad: 'Daño por frío < 8 °C',
    },
    infoNutricional: {
      Energía: '60 kcal / 100 g',
      Proteína: '0.8 g',
      'Grasa total': '0.4 g',
      Carbohidratos: '15 g',
      'Fibra dietética': '1.6 g',
      Azúcares: '13.7 g',
      'Vitamina C': '36.4 mg',
      'Vitamina A': '54 µg RAE',
      Folato: '43 µg',
    },
  },

  'pina-golden': {
    nombreCientifico: 'Ananas comosus (L.) Merr. cv. MD2 Golden',
    familia: 'Bromeliaceae',
    hsCode: '0804.30.00',
    origen: 'Ecuador',
    regionProduccion: 'Los Ríos, Esmeraldas, Pichincha, Manabí',
    puertoExportacion: 'Puerto de Guayaquil',
    temporadaDisponible: 'Todo el año (pico: Febrero – Mayo)',
    certificaciones: ['GlobalGAP', 'Rainforest Alliance', 'HACCP', 'Orgánico'],
    especificaciones: {
      'Peso por fruta': '1.2 – 2.5 kg',
      'Grados Brix': '14 – 17 °Brix',
      'Acidez titulable': '0.4 – 0.6 % ácido cítrico',
      'Color externo': 'Dorado uniforme > 25 % superficie',
      'Calibre exportación': '5 – 6 frutos por caja 12.5 kg',
      Madurez: 'C2 – C3 (escala de color Corona del Eje)',
      Corona: '≥ 2/3 de la longitud del fruto',
    },
    empaque: {
      'Peso neto caja': '12.5 kg',
      'Tipo de caja': 'Cartón corrugado doble muro',
      Distribución: '5 – 6 frutos / caja',
      'Funda interior': 'Polietileno perforado',
      Pallet: '72 cajas, 900 kg neto',
    },
    almacenamiento: {
      'Temperatura transporte': '7 – 10 °C',
      'Temperatura maduración': '18 – 22 °C',
      'Humedad relativa': '85 – 90 %',
      'Vida útil': '21 – 28 días',
      Precaución: 'Daño por frío a temperaturas < 7 °C',
    },
    infoNutricional: {
      Energía: '50 kcal / 100 g',
      Proteína: '0.5 g',
      'Grasa total': '0.1 g',
      Carbohidratos: '13.1 g',
      'Fibra dietética': '1.4 g',
      Azúcares: '9.9 g',
      'Vitamina C': '47.8 mg',
      Bromelina: 'Presente (enzima proteolítica)',
      Manganeso: '0.9 mg',
    },
  },

  'papaya-hawaiana': {
    nombreCientifico: 'Carica papaya L. (Solo / Hawaiian)',
    familia: 'Caricaceae',
    hsCode: '0807.20.00',
    origen: 'Ecuador',
    regionProduccion: 'Esmeraldas, Manabí, Santa Elena, Los Ríos',
    puertoExportacion: 'Puerto de Guayaquil',
    temporadaDisponible: 'Todo el año',
    certificaciones: ['GlobalGAP', 'HACCP'],
    especificaciones: {
      'Peso por fruta': '300 – 800 g',
      'Grados Brix': '12 – 14 °Brix mínimo',
      Pulpa: '45 – 60 % del peso total',
      'Color de exportación': 'Verde con < 10 % color amarillo',
      Firmeza: '8 – 12 lbf (Newton)',
      'Defectos superficiales': '≤ 2 % área afectada',
    },
    empaque: {
      'Caja 3.5 kg': '6 – 8 frutos',
      'Caja 5 kg': '9 – 12 frutos',
      Tipo: 'Cartón corrugado doble pared',
      Protección: 'Malla de espuma individual',
      Pallet: '96 cajas / pallet EUR',
    },
    almacenamiento: {
      Temperatura: '7 – 12 °C',
      'Humedad relativa': '85 – 90 %',
      'Vida útil': '21 – 28 días post cosecha',
      Sensibilidad: 'Daño por frío < 7 °C',
    },
    infoNutricional: {
      Energía: '43 kcal / 100 g',
      Proteína: '0.5 g',
      'Grasa total': '0.3 g',
      Carbohidratos: '10.8 g',
      'Fibra dietética': '1.7 g',
      'Vitamina C': '61.8 mg',
      'Vitamina A': '47 µg RAE',
      Papaína: 'Presente (enzima digestiva)',
      Folato: '37 µg',
    },
  },

  'coco-tropical': {
    nombreCientifico: 'Cocos nucifera L.',
    familia: 'Arecaceae',
    hsCode: '0801.19.00',
    origen: 'Ecuador',
    regionProduccion: 'Esmeraldas, Manabí, El Oro, Guayas',
    puertoExportacion: 'Puerto de Guayaquil / Esmeraldas',
    temporadaDisponible: 'Todo el año',
    certificaciones: ['HACCP', 'GlobalGAP'],
    especificaciones: {
      Tipo: 'Coco seco maduro / Coco tierno joven',
      'Peso fruta (seco)': '500 – 900 g sin cáscara',
      'Agua de coco (tierno)': '250 – 500 mL por fruta',
      'Contenido de aceite (copra)': '65 – 70 %',
      'Humedad (copra seco)': '≤ 6 %',
      Grado: 'A – sin defectos estructurales',
    },
    empaque: {
      'Seco maduro': '20 – 25 unidades en malla / saco',
      'Tierno joven': '9 – 12 unidades en caja de cartón',
      'Peso neto': '18 – 22 kg / caja',
      Pallet: '56 – 80 cajas / pallet',
    },
    almacenamiento: {
      'Coco maduro seco': '0 – 2 °C, hasta 2 meses',
      'Coco tierno': 'Ambiente fresco ≤ 25 °C, 2 – 3 semanas',
      'Humedad relativa': '80 – 85 %',
    },
    infoNutricional: {
      'Energía (pulpa)': '354 kcal / 100 g',
      Proteína: '3.3 g',
      'Grasa total': '33.5 g',
      'Ácidos grasos saturados': '29.7 g (láurico 12:0)',
      Carbohidratos: '15.2 g',
      'Fibra dietética': '9 g',
      Potasio: '356 mg',
      Manganeso: '1.5 mg',
    },
  },

  'yuca-premium': {
    nombreCientifico: 'Manihot esculenta Crantz',
    familia: 'Euphorbiaceae',
    hsCode: '0714.10.00',
    origen: 'Ecuador',
    regionProduccion: 'Guayas, Los Ríos, Manabí, Santo Domingo',
    puertoExportacion: 'Puerto de Guayaquil',
    temporadaDisponible: 'Todo el año',
    certificaciones: ['HACCP', 'GlobalGAP'],
    especificaciones: {
      'Peso por raíz': '0.5 – 2.0 kg',
      Longitud: '20 – 50 cm',
      Diámetro: '5 – 12 cm',
      'Color de pulpa': 'Blanca / Crema',
      Humedad: '60 – 65 %',
      Almidón: '28 – 32 %',
      'HCN (ácido cianhídrico)': '≤ 50 ppm (variedad dulce)',
      Defectos: '≤ 2 % fibrosidad o pudrición',
    },
    empaque: {
      'Presentación principal': 'Cajas de cartón 25 kg',
      Alternativa: 'Sacos de malla 25 kg',
      Encerado: 'Parafilm/cera natural para conservación',
      Pallet: '40 – 48 cajas / pallet',
    },
    almacenamiento: {
      Temperatura: '5 – 7 °C (encerada)',
      'Temperatura sin encerar': '13 – 16 °C',
      'Humedad relativa': '88 – 92 %',
      'Vida útil': '30 – 45 días (encerada); 7 días (sin encerar)',
    },
    infoNutricional: {
      Energía: '160 kcal / 100 g',
      Proteína: '1.4 g',
      'Grasa total': '0.3 g',
      Carbohidratos: '38.1 g',
      'Fibra dietética': '1.8 g',
      'Vitamina C': '20.6 mg',
      Potasio: '271 mg',
      Calcio: '16 mg',
    },
  },

  'camote-dulce': {
    nombreCientifico: 'Ipomoea batatas (L.) Lam.',
    familia: 'Convolvulaceae',
    hsCode: '0714.20.00',
    origen: 'Ecuador',
    regionProduccion: 'Manabí, Guayas, Los Ríos, El Oro',
    puertoExportacion: 'Puerto de Guayaquil',
    temporadaDisponible: 'Todo el año (pico: Junio – Octubre)',
    certificaciones: ['HACCP', 'GlobalGAP'],
    especificaciones: {
      'Peso por raíz': '150 – 400 g',
      Calibre: 'Diámetro 4 – 8 cm, Longitud 8 – 18 cm',
      'Color de pulpa': 'Naranja (betacaroteno) / Blanca / Morada',
      'Grados Brix': '8 – 12 °Brix',
      Almidón: '15 – 20 %',
      Humedad: '70 – 75 %',
      Defectos: '≤ 2 %',
    },
    empaque: {
      Presentación: 'Cajas de cartón 20 – 25 kg',
      Malla: 'Bolsas de malla 25 kg',
      'Distribución por pallet': '40 – 60 unidades / pallet',
    },
    almacenamiento: {
      Temperatura: '13 – 16 °C',
      'Humedad relativa': '85 – 90 %',
      'Vida útil': '30 – 60 días',
      'Curado previo': '7 – 10 días a 29 °C antes de almacenar',
    },
    infoNutricional: {
      Energía: '86 kcal / 100 g',
      Proteína: '1.6 g',
      'Grasa total': '0.1 g',
      Carbohidratos: '20.1 g',
      'Fibra dietética': '3 g',
      'Beta-caroteno': '8.5 mg (variedad naranja)',
      'Vitamina C': '2.4 mg',
      Potasio: '337 mg',
    },
  },

  'calabaza-premium': {
    nombreCientifico: 'Cucurbita maxima Duchesne',
    familia: 'Cucurbitaceae',
    hsCode: '0709.99.50',
    origen: 'Ecuador',
    regionProduccion: 'Guayas, Los Ríos, Manabí, Loja',
    puertoExportacion: 'Puerto de Guayaquil',
    temporadaDisponible: 'Todo el año (pico: Marzo – Agosto)',
    certificaciones: ['GlobalGAP', 'HACCP'],
    especificaciones: {
      'Peso por fruto': '2 – 8 kg',
      Diámetro: '25 – 40 cm',
      'Color exterior': 'Naranja intenso uniforme',
      Pulpa: 'Naranja, firme, sin fibras gruesas',
      'Grados Brix': '6 – 9 °Brix',
      'Espesor de pulpa': '3 – 5 cm',
      Defectos: '≤ 2 % superficie afectada',
    },
    empaque: {
      Presentación: 'Pallet/colchón 20 – 25 kg a granel',
      Caja: 'Cartón doble pared 20 kg',
      Distribución: '3 – 8 frutos / caja según peso',
    },
    almacenamiento: {
      Temperatura: '10 – 15 °C',
      'Humedad relativa': '60 – 70 %',
      'Vida útil': '30 – 90 días',
    },
    infoNutricional: {
      Energía: '26 kcal / 100 g',
      Proteína: '1 g',
      'Grasa total': '0.1 g',
      Carbohidratos: '6.5 g',
      'Fibra dietética': '0.5 g',
      'Beta-caroteno': '3.1 mg',
      'Vitamina C': '9 mg',
      Potasio: '340 mg',
    },
  },

  'cebolla-premium': {
    nombreCientifico: 'Allium cepa L.',
    familia: 'Amaryllidaceae',
    hsCode: '0703.10.00',
    origen: 'Ecuador',
    regionProduccion: 'Imbabura (San Pablo del Lago), Pichincha, Carchi',
    puertoExportacion: 'Puerto de Guayaquil',
    temporadaDisponible: 'Todo el año',
    certificaciones: ['GlobalGAP', 'HACCP'],
    especificaciones: {
      Diámetro: '5 – 8 cm (Calibre Medium – Jumbo)',
      Tipo: 'Cebolla amarilla / Roja / Blanca',
      'Piel exterior': 'Seca, ≥ 3 capas papiráceas',
      Pudrición: '≤ 1 %',
      Humedad: '≤ 85 %',
      Firmeza: 'Bulbo sólido sin brotación',
      Aromáticos: 'Contenido de aliína > 0.5 %',
    },
    empaque: {
      'Sacos de malla': '20 – 25 kg',
      'Caja de cartón': '20 kg',
      'Exportación preferida': 'Sacos de malla ventilados 25 kg',
      Pallet: '40 – 50 sacos / pallet',
    },
    almacenamiento: {
      Temperatura: '-1 – 0 °C (largo plazo) / 0 – 5 °C',
      'Humedad relativa': '65 – 70 %',
      'Vida útil': '1 – 6 meses (cura completa)',
      Ventilación: 'Importante: alta ventilación requerida',
    },
    infoNutricional: {
      Energía: '40 kcal / 100 g',
      Proteína: '1.1 g',
      Carbohidratos: '9.3 g',
      'Fibra dietética': '1.7 g',
      'Vitamina C': '7.4 mg',
      Folato: '19 µg',
      Potasio: '146 mg',
      Quercetina: '13 – 25 mg (polifenol)',
    },
  },

  'chayote-organico': {
    nombreCientifico: 'Sechium edule (Jacq.) Sw.',
    familia: 'Cucurbitaceae',
    hsCode: '0709.99.40',
    origen: 'Ecuador',
    regionProduccion: 'Pichincha, Loja, Carchi, Azuay',
    puertoExportacion: 'Puerto de Guayaquil',
    temporadaDisponible: 'Todo el año (pico: Marzo – Julio)',
    certificaciones: ['Orgánico', 'GlobalGAP', 'HACCP'],
    especificaciones: {
      'Peso por fruto': '150 – 400 g',
      Longitud: '8 – 15 cm',
      Color: 'Verde claro a verde oscuro',
      Textura: 'Firme, piel lisa o levemente acostillada',
      'Contenido de agua': '≈ 94 %',
      Defectos: '≤ 2 %',
    },
    empaque: {
      'Caja de cartón': '20 – 25 kg',
      'Bolsa interior': 'Polietileno perforado',
      Distribución: '40 – 80 frutos / caja',
    },
    almacenamiento: {
      Temperatura: '7 – 10 °C',
      'Humedad relativa': '90 – 95 %',
      'Vida útil': '30 – 40 días',
    },
    infoNutricional: {
      Energía: '19 kcal / 100 g',
      Proteína: '0.8 g',
      'Grasa total': '0.1 g',
      Carbohidratos: '4.5 g',
      'Fibra dietética': '1.7 g',
      'Vitamina C': '7.7 mg',
      Folato: '93 µg',
      Zinc: '0.7 mg',
    },
  },

  'palmito-organico': {
    nombreCientifico: 'Bactris gasipaes Kunth (Pejibaye)',
    familia: 'Arecaceae',
    hsCode: '2008.91.10',
    origen: 'Ecuador',
    regionProduccion: 'Esmeraldas, Sucumbíos, Napo, Orellana',
    puertoExportacion: 'Puerto de Guayaquil',
    temporadaDisponible: 'Todo el año',
    certificaciones: ['Orgánico', 'Comercio Justo', 'HACCP', 'BRC'],
    especificaciones: {
      'Diámetro del palmito': '2 – 5 cm',
      'Longitud en conserva': '7 – 9 cm',
      Color: 'Blanco marfil cremoso',
      Presentación: 'Entero / Rodajas / Juliana en conserva',
      'Líquido de cobertura': 'Salmuera al 2 – 2.5 % NaCl',
      'pH lata': '3.5 – 4.2 (acidificado)',
      Vacío: '≥ 25 cm Hg',
    },
    empaque: {
      'Lata 800 g': '24 latas / caja',
      'Lata 400 g': '24 latas / caja',
      'Frasco 400 g': '12 frascos / caja',
      'Caja maestra': 'Cartón corrugado 12 – 24 unidades',
      Pallet: '100 – 120 cajas / pallet',
    },
    almacenamiento: {
      'Producto en conserva': 'Temperatura ambiente ≤ 25 °C',
      'Palmito fresco': '0 – 4 °C; 7 – 10 días',
      'Vida útil (lata)': '36 – 48 meses desde fabricación',
    },
    infoNutricional: {
      Energía: '28 kcal / 100 g',
      Proteína: '2.7 g',
      'Grasa total': '0.6 g',
      Carbohidratos: '4.7 g',
      'Fibra dietética': '3.5 g',
      Potasio: '177 mg',
      Hierro: '3.1 mg',
      Calcio: '58 mg',
    },
    observaciones:
      'Ecuador exporta más del 80% del palmito en conserva consumido mundialmente. Certificación orgánica obtenida de cultivos bajo sombra en la Amazonía ecuatoriana.',
  },

  'cana-azucar': {
    nombreCientifico: 'Saccharum officinarum L.',
    familia: 'Poaceae',
    hsCode: '1212.99.10',
    origen: 'Ecuador',
    regionProduccion: 'Guayas (Milagro), Cañar, Azuay, Los Ríos',
    puertoExportacion: 'Puerto de Guayaquil',
    temporadaDisponible: 'Junio – Diciembre (zafra)',
    certificaciones: ['GlobalGAP', 'HACCP'],
    especificaciones: {
      'Longitud de tallo': '2.5 – 3.5 m',
      Diámetro: '3 – 5 cm',
      'Grados Brix': '18 – 23 °Brix',
      'Polarización (Pol)': '15 – 19 %',
      Pureza: '≥ 82 %',
      Fibra: '12 – 14 %',
      'Variedad principal': 'CC 85-92, Ragnar, INIAP H-65-7423',
    },
    empaque: {
      'Tallos frescos': 'Atados de 50 – 100 tallos',
      Troceado: 'Piezas 20 – 30 cm en sacos 25 kg',
      'A granel': 'Camiones / contenedores refrigerados',
    },
    almacenamiento: {
      Fresco: '2 – 4 semanas a 12 – 15 °C',
      Temperatura: '12 – 16 °C',
      'Humedad relativa': '80 – 85 %',
    },
    infoNutricional: {
      'Jugo (100 mL)': '54 kcal',
      'Azúcares totales': '13 g',
      Calcio: '11 mg',
      Hierro: '0.37 mg',
      Potasio: '42 mg',
    },
  },

  'jengibre-fresco': {
    nombreCientifico: 'Zingiber officinale Roscoe',
    familia: 'Zingiberaceae',
    hsCode: '0910.11.00',
    origen: 'Ecuador',
    regionProduccion: 'Los Ríos, Esmeraldas, Sucumbíos, Napo',
    puertoExportacion: 'Puerto de Guayaquil',
    temporadaDisponible: 'Todo el año (pico: Julio – Noviembre)',
    certificaciones: ['Orgánico', 'HACCP', 'GlobalGAP'],
    especificaciones: {
      Humedad: '78 – 83 %',
      Oleorresina: '≥ 4 % sobre seco',
      'Aceite esencial': '2 – 3 % sobre seco',
      'Gingerol (pungencia)': '5 – 8 mg/g',
      Apariencia: 'Rizoma fresco, firme, sin moho',
      Calibre: 'Mano > 50 g, grado A/B',
      Defectos: '≤ 3 %',
    },
    empaque: {
      'Caja de cartón': '10 – 13 kg',
      Sacos: '25 kg',
      'Presentación premium': 'Manos limpias 100 – 500 g / bandeja',
    },
    almacenamiento: {
      Temperatura: '10 – 13 °C',
      'Humedad relativa': '65 – 70 %',
      'Vida útil': '3 – 6 meses',
      Precaución: 'Sensible a temperaturas < 10 °C',
    },
    infoNutricional: {
      Energía: '80 kcal / 100 g',
      Proteína: '1.8 g',
      'Grasa total': '0.8 g',
      Carbohidratos: '17.8 g',
      'Fibra dietética': '2 g',
      'Vitamina C': '5 mg',
      Magnesio: '43 mg',
      Potasio: '415 mg',
    },
  },

  curcuma: {
    nombreCientifico: 'Curcuma longa L.',
    familia: 'Zingiberaceae',
    hsCode: '0910.30.00',
    origen: 'Ecuador',
    regionProduccion: 'Los Ríos, Esmeraldas, Sucumbíos',
    puertoExportacion: 'Puerto de Guayaquil',
    temporadaDisponible: 'Todo el año (pico: Agosto – Diciembre)',
    certificaciones: ['Orgánico', 'HACCP', 'GlobalGAP'],
    especificaciones: {
      'Curcumina (polvo)': '3.0 – 5.5 % HPLC',
      'Humedad (rizoma fresco)': '78 – 82 %',
      'Humedad (polvo)': '≤ 10 %',
      'Cenizas totales': '≤ 8 %',
      'Aceite esencial': '3 – 5 %',
      'Color (polvo)': 'Amarillo-naranja brillante ASTA ≥ 750',
      'Apariencia rizoma': 'Firme, sin pudrición, naranja interior',
    },
    empaque: {
      'Rizoma fresco': 'Cajas cartón 10 – 25 kg',
      Polvo: 'Bolsas kraft laminadas 25 kg',
      Retail: 'Bolsas zip 50 g – 1 kg',
    },
    almacenamiento: {
      'Rizoma fresco': '8 – 12 °C, 70 % humedad, 2 – 3 meses',
      Polvo: 'Lugar fresco/seco/oscuro < 25 °C, 24 meses',
    },
    infoNutricional: {
      'Energía (polvo)': '354 kcal / 100 g',
      Proteína: '7.8 g',
      'Grasa total': '9.9 g',
      Carbohidratos: '65 g',
      'Fibra dietética': '21 g',
      Curcumina: '≈ 3,500 mg / 100 g',
      Hierro: '41.5 mg',
      Manganeso: '7.8 mg',
    },
  },

  'name-tropical': {
    nombreCientifico: 'Dioscorea alata L.',
    familia: 'Dioscoreaceae',
    hsCode: '0714.90.10',
    origen: 'Ecuador',
    regionProduccion: 'Esmeraldas, Manabí, Sucumbíos, Los Ríos',
    puertoExportacion: 'Puerto de Guayaquil',
    temporadaDisponible: 'Marzo – Agosto',
    certificaciones: ['HACCP', 'GlobalGAP'],
    especificaciones: {
      'Peso por tubérculo': '0.5 – 5.0 kg',
      Longitud: '20 – 60 cm',
      'Color de pulpa': 'Blanca / Crema',
      Humedad: '68 – 72 %',
      Almidón: '22 – 28 %',
      Proteína: '2 – 4 %',
      Defectos: '≤ 3 %',
    },
    empaque: {
      'Caja de cartón': '25 kg',
      'Sacos de malla': '25 kg',
      'Presentación alternativa': 'Troceado al vacío 500 g – 2 kg',
    },
    almacenamiento: {
      Temperatura: '15 – 18 °C',
      'Humedad relativa': '65 – 70 %',
      'Vida útil': '3 – 6 meses',
    },
    infoNutricional: {
      Energía: '118 kcal / 100 g',
      Proteína: '1.5 g',
      Carbohidratos: '27.9 g',
      'Fibra dietética': '4.1 g',
      'Vitamina C': '17.1 mg',
      Potasio: '816 mg',
      'Vitamina B6': '0.3 mg',
    },
  },

  nampi: {
    nombreCientifico: 'Colocasia esculenta (L.) Schott',
    familia: 'Araceae',
    hsCode: '0714.90.20',
    origen: 'Ecuador',
    regionProduccion: 'Esmeraldas, Manabí, Los Ríos, Orellana',
    puertoExportacion: 'Puerto de Guayaquil',
    temporadaDisponible: 'Todo el año',
    certificaciones: ['HACCP', 'GlobalGAP'],
    especificaciones: {
      'Peso por cormo': '150 g – 1.0 kg',
      'Color de pulpa': 'Blanca con venas violáceas',
      Mucilaginosidad: 'Alta (reduce con cocción)',
      Almidón: '18 – 24 % (gránulos muy pequeños ≈ 1 µm)',
      'Oxalato de calcio': 'Presente – requiere cocción',
      Humedad: '70 – 75 %',
    },
    empaque: {
      'Caja de cartón': '20 – 25 kg',
      'Sacos de malla': '25 kg',
    },
    almacenamiento: {
      Temperatura: '7 – 10 °C',
      'Humedad relativa': '85 – 90 %',
      'Vida útil': '2 – 4 meses',
      Nota: 'No almacenar < 7 °C (daño por frío)',
    },
    infoNutricional: {
      Energía: '112 kcal / 100 g',
      Proteína: '1.5 g',
      Carbohidratos: '26.4 g',
      'Fibra dietética': '4.1 g',
      'Vitamina E': '2.4 mg',
      Potasio: '591 mg',
      Cobre: '0.2 mg',
    },
  },

  /* ─────────────────── MARINOS ─────────────────── */

  'camaron-blanco-premium': {
    nombreCientifico: 'Litopenaeus vannamei (Boone, 1931)',
    familia: 'Penaeidae',
    hsCode: '0306.17.90',
    origen: 'Ecuador',
    regionProduccion: 'Guayas, Manabí, El Oro, Santa Elena (Acuicultura)',
    puertoExportacion: 'Puerto de Guayaquil / Posorja',
    temporadaDisponible: 'Todo el año',
    certificaciones: ['HACCP', 'BAP', 'BRC', 'ASC', 'GlobalGAP'],
    especificaciones: {
      'Conteo (piezas/lb)': '16/20, 21/25, 26/30, 31/40, 41/50',
      Presentación: 'IQF (Individual Quick Frozen)',
      Procesado: 'Entero con cabeza (HLSO) / Sin cabeza (HOSO) / P&D',
      Glaseo: '≤ 15 % sobre peso declarado',
      Histamina: '< 100 ppm',
      'Temperatura de congelación': '-18 °C o menor',
      Color: 'Gris-verdoso uniforme; sin decoloración',
      Humedad: '≤ 80 %',
    },
    empaque: {
      'Bloque IQF': '2 kg por bloque',
      'Bloques por caja': '10 bloques = 20 kg bruto',
      'Caja maestra': 'Cartón polyestireno',
      'Liner interior': 'Bolsa polietileno sellada al vacío',
      Pallet: '1,000 kg neto / pallet',
      Contenedor: "40' HC Reefer a -20 °C",
    },
    almacenamiento: {
      Temperatura: '-18 °C o inferior',
      'Vida útil': '24 meses desde fecha de producción',
      Transporte: 'Cadena de frío continua ≤ -18 °C',
      Descongelación: 'Bajo agua fría corriente o refrigeración 4 °C',
    },
    infoNutricional: {
      Energía: '71 kcal / 100 g',
      Proteína: '13.6 g',
      'Grasa total': '0.9 g',
      'Omega-3 (EPA+DHA)': '0.54 g',
      Carbohidratos: '0 g',
      Colesterol: '105 mg',
      Sodio: '119 mg',
      Selenio: '38 µg',
    },
    observaciones:
      'Ecuador es el tercer mayor exportador mundial de camarón blanco. Producción en sistemas de acuicultura extensiva-intensiva con trazabilidad completa desde la larva hasta el producto final.',
  },

  'larvas-camaron-postlarva': {
    nombreCientifico: 'Litopenaeus vannamei PL12 – PL18',
    familia: 'Penaeidae',
    hsCode: '0306.99.10',
    origen: 'Ecuador',
    regionProduccion: 'Guayas, Manabí, El Oro (Laboratorios de Larvas)',
    puertoExportacion: 'Vía aérea desde Guayaquil (GYE)',
    temporadaDisponible: 'Todo el año',
    certificaciones: ['HACCP', 'BAP', 'SPF Certificado'],
    especificaciones: {
      Estadio: 'PL12 a PL18',
      'Tamaño promedio': '10 – 15 mm',
      'Estado sanitario': 'SPF (Libre de patógenos específicos)',
      'Tasa de supervivencia': '≥ 90 %',
      'Densidad de empaque': '500 – 1,000 PL / bolsa',
      'Temperatura de transporte': '28 – 30 °C',
    },
    empaque: {
      'Bolsa de oxígeno': 'Doble funda PE con O₂ puro',
      'Caja térmica': 'Poliestireno expandido',
      'Tiempo máximo transporte': '24 – 48 horas',
    },
    almacenamiento: {
      'Agua de transporte': '28 – 30 °C',
      Salinidad: '28 – 35 ppt',
      'Oxígeno disuelto': '≥ 6 ppm',
    },
    observaciones:
      'Las postlarvas son certificadas SPF y provienen de reproductores seleccionados genéticamente. Se incluye certificado sanitario oficial AGROCALIDAD / IESS.',
  },

  'atun-fresco-pacifico': {
    nombreCientifico: 'Thunnus albacares (Yellowfin) / Katsuwonus pelamis (Listado)',
    familia: 'Scombridae',
    hsCode: '0302.31.00',
    origen: 'Ecuador',
    regionProduccion: 'Océano Pacífico – Puertos Manta, Salinas, Posorja',
    puertoExportacion: 'Puerto de Manta / Puerto de Guayaquil',
    temporadaDisponible: 'Todo el año (temporada alta: Mayo – Septiembre)',
    certificaciones: ['HACCP', 'BRC', 'MSC (disponible)'],
    especificaciones: {
      'Presentación principal': 'Loins / Entero eviscerado / Fresco en hielo',
      Histamina: '< 100 ppm (fresco) / < 200 ppm (proceso)',
      'pH de pulpa': '5.8 – 6.2',
      'Temperatura interna': '0 – 4 °C (fresco) / -20 °C (congelado)',
      'Color de pulpa': 'Rojo brillante (fresco); rosado (loin congelado)',
      'TVN (nitrógeno volátil)': '< 25 mg/100 g',
      'Peso entero': '10 – 120 kg por ejemplar (yellowfin)',
    },
    empaque: {
      'Loins congelados': 'Caja 6.8 kg, 4 cajas / máster',
      'Entero en hielo': 'Contenedor isotérmico con hielo en escamas',
      'Relación hielo:pescado': '1:1',
    },
    almacenamiento: {
      'Fresco en hielo': '0 – 2 °C, ≤ 15 días',
      'Loin congelado': '-20 °C o inferior, 18 meses',
      'Transporte fresco': 'Camión frigorífico 0 – 4 °C',
    },
    infoNutricional: {
      Energía: '109 kcal / 100 g',
      Proteína: '24.4 g',
      'Grasa total': '0.5 g',
      'Omega-3 (DHA+EPA)': '0.3 g',
      Sodio: '45 mg',
      Selenio: '90 µg',
      'Vitamina D': '4.5 µg',
      'Vitamina B12': '2.2 µg',
    },
  },

  /* ─────────────────── OTROS / ESPECIALIDAD ─────────────────── */

  'cacao-fino-aroma': {
    nombreCientifico: 'Theobroma cacao L. (variedad Nacional / Arriba)',
    familia: 'Malvaceae (Sterculiaceae)',
    hsCode: '1801.00.10',
    origen: 'Ecuador',
    regionProduccion: 'Los Ríos, Manabí, Esmeraldas, Napo (Cacao Arriba)',
    puertoExportacion: 'Puerto de Guayaquil',
    temporadaDisponible: 'Mayo – Julio (principal); Octubre – Diciembre (segunda cosecha)',
    certificaciones: ['Orgánico', 'Comercio Justo', 'HACCP', 'BRC', 'Rainforest Alliance'],
    especificaciones: {
      Variedad: 'Nacional / CCN-51 (separadas en exportación)',
      Fermentación: '≥ 75 % de granos bien fermentados',
      Humedad: '≤ 7.5 %',
      'Contenido de grasa (manteca)': '40 – 52 % sobre seco',
      'Tamaño promedio grano': '≥ 1 g / grano (100 granos > 100 g)',
      'Granos enteros': '≥ 95 %',
      'Granos mohosos': '≤ 3 %',
      'Granos pizarrosos': '≤ 3 %',
      'Temperatura de almacenaje': '≤ 20 °C',
    },
    empaque: {
      'Saco estándar': '60 kg – yute / polipropileno + liner polietileno',
      'Sacos especiales': '25 kg para mercados premium',
      "Por contenedor (20')": '≈ 280 sacos de 60 kg = 16.8 TM',
      Etiquetado: 'Lote, fecha, finca, certificación, grado',
    },
    almacenamiento: {
      Temperatura: '≤ 20 °C',
      'Humedad relativa ambiente': '< 65 %',
      'Vida útil grano': '12 – 18 meses en condiciones adecuadas',
      Precaución: 'Evitar olores fuertes (absorción)',
    },
    infoNutricional: {
      'Energía (grano seco)': '228 kcal / 100 g',
      Proteína: '19.6 g',
      'Grasa total': '13.7 g',
      Carbohidratos: '57.9 g',
      'Fibra dietética': '33.2 g',
      Teobromina: '2,056 mg',
      Magnesio: '499 mg',
      Hierro: '13.9 mg',
    },
    observaciones:
      'Ecuador produce el 70 % del cacao fino de aroma del mundo (clasificación ICCO). La variedad Nacional "Arriba" tiene perfil floral único con notas de violeta. Reconocido como el mejor cacao del mundo en múltiples competencias internacionales.',
  },

  'cafe-arabica-altura': {
    nombreCientifico: 'Coffea arabica L. (Typica, Bourbon, Caturra, Geisha)',
    familia: 'Rubiaceae',
    hsCode: '0901.11.10',
    origen: 'Ecuador',
    regionProduccion: 'Loja, Zamora Chinchipe, Manabí, Galápagos, Pichincha',
    puertoExportacion: 'Puerto de Guayaquil / Aeropuerto Quito',
    temporadaDisponible: 'Junio – Noviembre (Loja); Todo el año (Galápagos)',
    certificaciones: ['Orgánico', 'Comercio Justo', 'HACCP', 'Rainforest Alliance'],
    especificaciones: {
      'Grado exportación': 'Strictly Hard Bean (SHB) / Hard Bean (HB)',
      'Altitud cultivo': '1,500 – 2,200 msnm',
      'Malla (screen)': '14+ (grano verde)',
      'Humedad grano': '≤ 12 %',
      'Defectos (300 g)': '≤ 8 defectos totales',
      'Puntaje de taza': '80+ puntos SCA (Specialty)',
      Proceso: 'Lavado / Natural / Honey disponibles',
      'Perfil sensorial': 'Floral, cítrico, frutal, caramelo, chocolate',
    },
    empaque: {
      'Saco estándar': '60 kg jute + grain-pro bag',
      'GrainPro liner': 'Barrera de humedad y oxígeno',
      'Exportación retail': 'Bolsas desgasificadas 250 g / 1 kg N₂',
    },
    almacenamiento: {
      'Grano verde': '< 65 % HR, < 20 °C, 12 – 18 meses',
      'Tostado entero': '< 4 semanas (sin desgasificar)',
      Molido: '< 2 semanas (bolsa cerrada)',
      'Congelado (especialidad)': '-18 °C sellado al vacío, 12 meses',
    },
    infoNutricional: {
      'Energía (bebida preparada)': '2 kcal / 100 mL',
      Cafeína: '95 – 165 mg por taza 8 oz',
      'Ácido clorogénico': '200 – 550 mg por taza',
      'Niacina (B3)': '0.7 mg / 100 mL',
      Magnesio: '7 mg / 100 mL',
    },
    observaciones:
      'El café de Loja y Galápagos goza de reconocimiento internacional. Las variedades Geisha de los Andes ecuatorianos han alcanzado puntajes SCA superiores a 90 puntos.',
  },

  'rosas-rojas-premium': {
    nombreCientifico: 'Rosa hybrida (Freedom, Explorer, Charlotte, Forever Young)',
    familia: 'Rosaceae',
    hsCode: '0603.11.00',
    origen: 'Ecuador',
    regionProduccion: 'Pichincha, Cotopaxi, Imbabura, Azuay (2,800 – 3,200 msnm)',
    puertoExportacion: 'Aeropuerto Quito (UIO) / Aeropuerto Guayaquil (GYE)',
    temporadaDisponible: 'Todo el año (alta demanda: Enero – Febrero, Mayo, Noviembre)',
    certificaciones: ['Rainforest Alliance', 'Flor Ecuador', 'BASC', 'GlobalGAP'],
    especificaciones: {
      'Longitud de tallo': '40 / 50 / 60 / 70 / 80 cm',
      'Diámetro de botón': '4.5 – 7.0 cm (en madurez de exportación)',
      'Apertura de exportación': '1 – 2 (escala de 1 a 6)',
      'Vida en florero': '14 – 21 días (con condicionador)',
      Follaje: 'Verde brillante sin manchas, ≥ 5 hojas',
      Espinas: 'Removidas en los últimos 20 cm',
      Defectos: '0 en calibres premium (USDA Grade 1)',
    },
    empaque: {
      'Ramo (bunch)': '25 tallos / ramo',
      'Half Box (HB)': '25 – 30 ramos, 12 – 15 lbs',
      'Full Box (FB)': '50 – 60 ramos, 25 – 28 lbs',
      'Caja de hidratación': 'Cartón con bandeja de agua',
      'Empaque en seco': 'Papel kraft + film plástico',
      'Temperatura en vuelo': '2 – 4 °C',
    },
    almacenamiento: {
      Temperatura: '1 – 2 °C',
      'Humedad relativa': '90 – 95 %',
      'Vida útil post corte': '14 – 21 días (en frío)',
      Hidratación: 'Solución preservante con biocida y sacarosa',
      Transporte: 'Cadena de frío aérea continua',
    },
    observaciones:
      'Ecuador produce las rosas con botones más grandes del mundo gracias a la altitud y radiación solar de los Andes. Es el tercer mayor exportador mundial de flores frescas cortadas.',
  },

  'nueces-macadamia': {
    nombreCientifico: 'Macadamia integrifolia Maiden & Betche',
    familia: 'Proteaceae',
    hsCode: '0802.62.00',
    origen: 'Ecuador',
    regionProduccion: 'Pichincha, Imbabura, Cotopaxi, Esmeraldas',
    puertoExportacion: 'Puerto de Guayaquil',
    temporadaDisponible: 'Marzo – Agosto',
    certificaciones: ['Orgánico', 'GlobalGAP', 'HACCP'],
    especificaciones: {
      'Diámetro del kernel': '18 – 22 mm',
      Humedad: '≤ 1.5 %',
      'Recuperación de kernel': '22 – 25 %',
      'Contenido de grasa': '75 – 80 %',
      'Ácido oleico (Omega-9)': '≈ 60 %',
      Grado: 'Style 1 (enteras) / Style 4S (mitades)',
      'Aflatoxinas totales': '≤ 10 ppb',
    },
    empaque: {
      'Bolsa vacuum': '5 kg',
      'Caja maestra': '20 kg (4 × 5 kg)',
      'Lata hermética': '500 g – 3 kg para retail',
      'Atmósfera modificada': 'N₂ / CO₂ para extensión de vida útil',
    },
    almacenamiento: {
      'Largo plazo': '-18 °C, 24 meses',
      'Corto plazo': '15 – 18 °C, < 65 % HR, 12 meses',
      'Temperatura óptima': '0 – 4 °C para máxima frescura',
    },
    infoNutricional: {
      Energía: '718 kcal / 100 g',
      Proteína: '7.9 g',
      'Grasa total': '75.8 g',
      'Ácidos grasos monoinsaturados': '58.9 g',
      Carbohidratos: '13.8 g',
      'Fibra dietética': '8.6 g',
      Manganeso: '4.1 mg',
      'Tiamina (B1)': '1.2 mg',
    },
  },

  'nueces-pecanas': {
    nombreCientifico: 'Carya illinoinensis (Wangenh.) K.Koch',
    familia: 'Juglandaceae',
    hsCode: '0802.90.10',
    origen: 'Ecuador',
    regionProduccion: 'Pichincha, Cotopaxi, Imbabura (adaptación tropical)',
    puertoExportacion: 'Puerto de Guayaquil',
    temporadaDisponible: 'Abril – Septiembre',
    certificaciones: ['Orgánico', 'GlobalGAP', 'HACCP'],
    especificaciones: {
      Diámetro: '15 – 20 mm',
      Humedad: '≤ 3 %',
      'Relleno (fill)': '≥ 75 %',
      'Contenido de grasa': '71 – 73 %',
      'Calidad kernel': 'Color crema claro, sin oscurecimiento',
      Aflatoxinas: '≤ 4 ppb B1 / ≤ 10 ppb totales',
    },
    empaque: {
      'Bolsa vacuum': '5 kg',
      'Caja maestra': '20 kg',
      Retail: 'Bolsas resellables 150 g – 1 kg',
    },
    almacenamiento: {
      Congelado: '-18 °C, 24 meses',
      Refrigerado: '4 – 10 °C, 6 meses',
      'Temperatura ambiente': '< 20 °C, 3 meses',
    },
    infoNutricional: {
      Energía: '691 kcal / 100 g',
      Proteína: '9.2 g',
      'Grasa total': '72 g',
      'Ácidos grasos monoinsaturados': '40.8 g',
      Carbohidratos: '13.9 g',
      'Fibra dietética': '9.6 g',
      Zinc: '4.5 mg',
      Magnesio: '121 mg',
    },
  },

  'almendras-tropicales': {
    nombreCientifico: 'Terminalia catappa L.',
    familia: 'Combretaceae',
    hsCode: '0802.90.90',
    origen: 'Ecuador',
    regionProduccion: 'Esmeraldas, Manabí, Guayas (costa)',
    puertoExportacion: 'Puerto de Guayaquil',
    temporadaDisponible: 'Junio – Octubre',
    certificaciones: ['Orgánico', 'HACCP'],
    especificaciones: {
      'Tamaño kernel': '15 – 20 mm',
      Humedad: '≤ 8 %',
      'Contenido de grasa': '48 – 54 %',
      Proteína: '20 – 25 %',
      'Color kernel': 'Blanco-crema sin oxidación',
    },
    empaque: {
      'Caja de cartón': '10 kg',
      'Bolsa vacuum': '500 g – 5 kg',
      Atmósfera: 'Sellado con N₂ para preservación',
    },
    almacenamiento: {
      Temperatura: '12 – 15 °C',
      'Humedad relativa': '< 60 %',
      'Vida útil': '6 – 12 meses',
    },
    infoNutricional: {
      Energía: '574 kcal / 100 g',
      Proteína: '21 g',
      'Grasa total': '49 g',
      Carbohidratos: '20 g',
      'Vitamina E': '9 mg',
      Calcio: '264 mg',
      Hierro: '7.5 mg',
    },
  },

  /* ─────────────────── PLANTAS / ÁRBOLES ─────────────────── */

  'arboles-mango': {
    nombreCientifico: 'Mangifera indica L. (Tommy Atkins, Haden, Kent, Ataulfo)',
    familia: 'Anacardiaceae',
    hsCode: '0602.90.90',
    origen: 'Ecuador',
    regionProduccion: 'Guayas, Manabí, El Oro (viveros certificados)',
    puertoExportacion: 'Aeropuerto Quito (GYE/UIO) / Puerto de Guayaquil',
    temporadaDisponible: 'Todo el año',
    certificaciones: ['GlobalGAP', 'AGROCALIDAD certificado fitosanitario'],
    especificaciones: {
      'Tipo de propagación': 'Injerto de yema / estaca',
      Portainjerto: 'Mango criollo o Turpentine',
      'Altura de despacho': '60 – 100 cm',
      'Tiempo en vivero': '6 – 12 meses',
      'Estado sanitario': 'Libre de Xanthomonas campestris pv. mangiferaeindicae',
      Certificado: 'Fitosanitario oficial AGROCALIDAD',
    },
    empaque: {
      Contenedor: 'Maceta 1 – 3 galones',
      'Por pallet': '15 – 20 plantas',
      Protección: 'Funda plástica + guía tutora',
      Raíces: 'Cepellón de suelo o sustrato estabilizado',
    },
    almacenamiento: {
      'Temperatura transporte': '18 – 28 °C',
      Irrigación: 'Cada 3 – 5 días (contenedor)',
      'Tiempo máximo tránsito': '10 – 14 días con raíz en cepellón',
    },
    observaciones:
      'Todos los árboles de exportación requieren certificado fitosanitario AGROCALIDAD. Se puede exportar con permiso de importación del país destino.',
  },

  'arboles-aguacate': {
    nombreCientifico: 'Persea americana Mill. cv. Hass (injertado)',
    familia: 'Lauraceae',
    hsCode: '0602.90.90',
    origen: 'Ecuador',
    regionProduccion: 'Imbabura, Pichincha (viveros 2,000 – 2,500 msnm)',
    puertoExportacion: 'Aeropuerto Quito (UIO)',
    temporadaDisponible: 'Todo el año',
    certificaciones: ['GlobalGAP', 'AGROCALIDAD certificado fitosanitario'],
    especificaciones: {
      Variedad: 'Hass (injertado en portainjerto mexicano/guatemalteco)',
      'Altura de despacho': '60 – 80 cm',
      'Tiempo en vivero': '6 – 8 meses post injerto',
      'Estado sanitario': 'Libre de Phytophthora cinnamomi',
      'Diámetro de tallo': '≥ 8 mm en punto de injerto',
    },
    empaque: {
      Maceta: '1 – 3 galones',
      'Por pallet': '15 – 20 plantas',
      Protección: 'Funda + tutor',
    },
    almacenamiento: {
      Temperatura: '15 – 22 °C',
      Riego: 'Sustrato húmedo no saturado',
    },
  },

  'arboles-citricos': {
    nombreCientifico: 'Citrus sinensis / C. limon / C. reticulata (injertados)',
    familia: 'Rutaceae',
    hsCode: '0602.90.90',
    origen: 'Ecuador',
    regionProduccion: 'Guayas, Manabí, El Oro (viveros costeros)',
    puertoExportacion: 'Puerto de Guayaquil / Aeropuerto Guayaquil',
    temporadaDisponible: 'Todo el año',
    certificaciones: ['GlobalGAP', 'AGROCALIDAD certificado fitosanitario'],
    especificaciones: {
      Variedades: 'Naranja Valencia, Limón Tahití, Mandarina, Tangelo',
      'Tipo de injerto': 'Yema T / chip budding en portainjerto Citrumelo',
      Altura: '50 – 70 cm',
      'Tiempo vivero': '5 – 7 meses',
      Certificado: 'Libre de Xylella fastidiosa, CTV, HLB (Huanglongbing)',
    },
    empaque: {
      Maceta: '1 – 3 galones',
      'Caja de transporte': 'Cartón ventilado con separadores',
      'Por pallet': '15 – 25 plantas',
    },
    almacenamiento: {
      Temperatura: '18 – 28 °C',
      Luz: 'Plena exposición o 40 % sombra malla raschel',
      Riego: 'Cada 2 – 3 días',
    },
  },
};

/** Returns the ficha técnica for a given product slug, or null if not mapped. */
export function getFichaTecnica(slug: string): FichaTecnica | null {
  return FICHAS[slug] ?? null;
}

/** Returns all slugs that have a ficha técnica defined. */
export function getFichasSlugs(): string[] {
  return Object.keys(FICHAS);
}
