-- =============================================
-- ZIVAH International - Supabase Auth Setup
-- Role-Based Access Control (RBAC)
-- =============================================

-- =============================================
-- 1. Custom Types for Roles and Permissions
-- =============================================

-- User roles for the application
CREATE TYPE public.app_role AS ENUM (
  'admin',         -- Full access to everything
  'sales_manager', -- Manage quotes, products, pricing, team
  'sales_rep',     -- Manage assigned quotes, view products
  'viewer'         -- Read-only access
);

-- Permissions for granular access control
CREATE TYPE public.app_permission AS ENUM (
  -- Quote permissions
  'quotes.view',
  'quotes.create',
  'quotes.edit',
  'quotes.delete',
  'quotes.assign',
  -- Product permissions
  'products.view',
  'products.create',
  'products.edit',
  'products.delete',
  -- Category permissions
  'categories.view',
  'categories.create',
  'categories.edit',
  'categories.delete',
  -- Pricing permissions
  'pricing.view',
  'pricing.edit',
  -- Contact/Newsletter permissions
  'contacts.view',
  'contacts.edit',
  'contacts.delete',
  -- Settings permissions
  'settings.view',
  'settings.edit',
  -- Activity log permissions
  'activity.view'
);

-- =============================================
-- 2. Profiles Table (extends auth.users)
-- =============================================

CREATE TABLE public.profiles (
  id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  full_name TEXT,
  avatar_url TEXT,
  role public.app_role DEFAULT 'viewer'::public.app_role NOT NULL,
  department TEXT,
  phone TEXT,
  company TEXT DEFAULT 'ZIVAH International',
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.profiles IS 'User profiles extending Supabase auth.users';

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Create indexes
CREATE INDEX idx_profiles_role ON public.profiles(role);
CREATE INDEX idx_profiles_is_active ON public.profiles(is_active);
CREATE INDEX idx_profiles_email ON public.profiles(email);

-- =============================================
-- 3. Role Permissions Mapping Table
-- =============================================

CREATE TABLE public.role_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role public.app_role NOT NULL,
  permission public.app_permission NOT NULL,
  UNIQUE (role, permission)
);

COMMENT ON TABLE public.role_permissions IS 'Maps roles to their allowed permissions';

-- Insert default permissions for each role
INSERT INTO public.role_permissions (role, permission) VALUES
  -- Admin has all permissions
  ('admin', 'quotes.view'),
  ('admin', 'quotes.create'),
  ('admin', 'quotes.edit'),
  ('admin', 'quotes.delete'),
  ('admin', 'quotes.assign'),
  ('admin', 'products.view'),
  ('admin', 'products.create'),
  ('admin', 'products.edit'),
  ('admin', 'products.delete'),
  ('admin', 'categories.view'),
  ('admin', 'categories.create'),
  ('admin', 'categories.edit'),
  ('admin', 'categories.delete'),
  ('admin', 'pricing.view'),
  ('admin', 'pricing.edit'),
  ('admin', 'contacts.view'),
  ('admin', 'contacts.edit'),
  ('admin', 'contacts.delete'),
  ('admin', 'settings.view'),
  ('admin', 'settings.edit'),
  ('admin', 'activity.view'),

  -- Sales Manager permissions
  ('sales_manager', 'quotes.view'),
  ('sales_manager', 'quotes.create'),
  ('sales_manager', 'quotes.edit'),
  ('sales_manager', 'quotes.delete'),
  ('sales_manager', 'quotes.assign'),
  ('sales_manager', 'products.view'),
  ('sales_manager', 'products.create'),
  ('sales_manager', 'products.edit'),
  ('sales_manager', 'categories.view'),
  ('sales_manager', 'pricing.view'),
  ('sales_manager', 'pricing.edit'),
  ('sales_manager', 'contacts.view'),
  ('sales_manager', 'contacts.edit'),
  ('sales_manager', 'activity.view'),

  -- Sales Rep permissions
  ('sales_rep', 'quotes.view'),
  ('sales_rep', 'quotes.create'),
  ('sales_rep', 'quotes.edit'),
  ('sales_rep', 'products.view'),
  ('sales_rep', 'categories.view'),
  ('sales_rep', 'pricing.view'),
  ('sales_rep', 'contacts.view'),

  -- Viewer permissions (read-only)
  ('viewer', 'quotes.view'),
  ('viewer', 'products.view'),
  ('viewer', 'categories.view'),
  ('viewer', 'pricing.view');

-- =============================================
-- 4. Auto-create profile on user signup
-- =============================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, avatar_url)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name'),
    NEW.raw_user_meta_data->>'avatar_url'
  );
  RETURN NEW;
END;
$$;

-- Trigger to create profile on signup
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =============================================
-- 5. Auth Hook: Add user_role to JWT claims
-- =============================================

CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event JSONB)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  claims JSONB;
  user_role public.app_role;
BEGIN
  -- Fetch the user role from profiles table
  SELECT role INTO user_role
  FROM public.profiles
  WHERE id = (event->>'user_id')::uuid;

  claims := event->'claims';

  IF user_role IS NOT NULL THEN
    claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
  ELSE
    claims := jsonb_set(claims, '{user_role}', '"viewer"');
  END IF;

  event := jsonb_set(event, '{claims}', claims);

  RETURN event;
END;
$$;

-- Grant permissions for the auth hook
GRANT USAGE ON SCHEMA public TO supabase_auth_admin;

GRANT EXECUTE
  ON FUNCTION public.custom_access_token_hook
  TO supabase_auth_admin;

REVOKE EXECUTE
  ON FUNCTION public.custom_access_token_hook
  FROM authenticated, anon, public;

GRANT ALL
  ON TABLE public.profiles
  TO supabase_auth_admin;

-- =============================================
-- 6. Authorization Helper Function
-- =============================================

CREATE OR REPLACE FUNCTION public.authorize(requested_permission public.app_permission)
RETURNS BOOLEAN AS $$
DECLARE
  bind_permissions INT;
  user_role public.app_role;
BEGIN
  -- Get user role from JWT claims
  SELECT (auth.jwt() ->> 'user_role')::public.app_role INTO user_role;

  -- Count matching permissions
  SELECT COUNT(*)
  INTO bind_permissions
  FROM public.role_permissions
  WHERE role_permissions.permission = requested_permission
    AND role_permissions.role = user_role;

  RETURN bind_permissions > 0;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = '';

-- =============================================
-- 7. RLS Policies for Profiles
-- =============================================

-- Allow users to view their own profile
CREATE POLICY "Users can view own profile"
  ON public.profiles FOR SELECT
  TO authenticated
  USING (auth.uid() = id);

-- Allow admins to view all profiles
CREATE POLICY "Admins can view all profiles"
  ON public.profiles FOR SELECT
  TO authenticated
  USING ((auth.jwt() ->> 'user_role') = 'admin');

-- Allow users to update their own profile (except role)
CREATE POLICY "Users can update own profile"
  ON public.profiles FOR UPDATE
  TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (
    auth.uid() = id AND
    -- Prevent users from changing their own role
    role = (SELECT role FROM public.profiles WHERE id = auth.uid())
  );

-- Allow admins to update any profile including roles
CREATE POLICY "Admins can update all profiles"
  ON public.profiles FOR UPDATE
  TO authenticated
  USING ((auth.jwt() ->> 'user_role') = 'admin');

-- Allow supabase_auth_admin to read profiles (for the auth hook)
CREATE POLICY "Allow auth admin to read profiles"
  ON public.profiles FOR SELECT
  TO supabase_auth_admin
  USING (true);

-- =============================================
-- 8. Updated_at Trigger for Profiles
-- =============================================

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- =============================================
-- 9. Initial Admin User (Run manually after first signup)
-- =============================================
-- After your first admin signs up, run this to set their role:
-- UPDATE public.profiles SET role = 'admin' WHERE email = 'admin@zivahinternational.com';
